os: linux
dist: bionic
language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy
install:
  - pip uninstall -y nose
  - pip install -r requirements.txt
script:
  - python setup.py build_tests || python setup.py egg_info; python selftest.py
